<?php
//======================================================================//
//== About art_has_rel.class.php
//==--------------------------------------------------------------------//
//== This file is generated by mysql.class.php of puppets library.
//== Copyright (c) 2009-2011 - MAQPRINT
//== Licensed under the GPL version 2.0 license.
//== See LICENSE file or
//== http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
//==--------------------------------------------------------------------//
//== Contributor : Erwan LE LOSTEC
//== Contributor : Patrick PERONNY
//======================================================================//
class art_has_rel
{/** @class art_has_rel
  * @brief art_has_rel table management.
  * Provides different methods for read and write in a art_has_rel table.
  **/
	public $artrel_id;
	public $art_id;
	public $rel_id;
	public $artrel_order;

	private $mysql;

	public function __construct($artrel_id = null)
	{/** @function art_has_rel()
	  * Create a new art_has_rel object.
	  * 
	  * @param	artrel_id		<int(11)>	the id of art_has_rel to load
	  * 
	  * @return	<boolean>
	  **/
		global $mysql;

		$this->mysql	= $mysql;

		$this->artrel_id	= $this->mysql->secure($artrel_id);
		$this->art_id	= null;
		$this->rel_id	= null;
		$this->artrel_order	= null;
		if($artrel_id != null)
		{
			$req_art_has_rel = $this->mysql->query("SELECT * FROM art_has_rel WHERE artrel_id='".$this->artrel_id."' LIMIT 1;");
			if($req_art_has_rel->numRows() > 0)
			{
				$obj_art_has_rel = $req_art_has_rel->fetchRow();
				$this->artrel_id	= $obj_art_has_rel->artrel_id;
				$this->art_id	= $obj_art_has_rel->art_id;
				$this->rel_id	= $obj_art_has_rel->rel_id;
				$this->artrel_order	= $obj_art_has_rel->artrel_order;
			}
			else
			{
				error_log("Error while loading art_has_rel, there no art_has_rel of id : $artrel_id.");
				throw new Exception("Error while loading art_has_rel, there no art_has_rel of id : $artrel_id.");
				return false; 
			};
		}
		return true;
	}
	public function save()
	{/** @function save()
	 * Insert or update a art_has_rel.
	 *
	 * @return	<mixed>		return false or the id of inserted/updated art_has_rel.
	 **/
		$flag_error = false;

		$this->mysql->beginTransactions();

		if(empty($this->artrel_id))
		{//-- Insert
			if(!$this->mysql->query("INSERT INTO art_has_rel (art_id, rel_id, artrel_order)
									VALUES (".$this->mysql->secure($this->art_id).", ".$this->mysql->secure($this->rel_id).", ".$this->mysql->secure($this->artrel_order).");")) { $flag_error = true; };
			$this->artrel_id = $this->mysql->lastInsertId();
		}
		else
		{//-- Update
			if(!$this->mysql->query("UPDATE art_has_rel SET art_id='".$this->mysql->secure($this->art_id)."', rel_id='".$this->mysql->secure($this->rel_id)."', artrel_order='".$this->mysql->secure($this->artrel_order)."'
									WHERE artrel_id=".$this->mysql->secure($this->artrel_id).";")) { $flag_error = true; };
		}

		$this->mysql->endTransactions($flag_error);

		if($flag_error)
		{
			error_log("Error while inserting/updating the art_has_rel.");
			throw new Exception("Error while inserting/updating the art_has_rel.");
			return false;
		}
		else
		{
			return $this->artrel_id;
		};
	}
	public static function delete($artrel_id)
	{/** @function delete()
	 * Delete the art_has_rel.
	 *
	 * @param	artrel_id	<int(11)>	the id of the art_has_rel to delete
	 *
	 * @return	<boolean>
	 **/
		global $mysql;

		$flag_error = false;

		$mysql->beginTransactions();

		if(!$mysql->query("DELETE FROM art_has_rel WHERE artrel_id=".$mysql->secure($artrel_id).";")) { $flag_error = true; };

		$mysql->endTransactions($flag_error);

		if($flag_error)
		{
			error_log("Error while deleting the art_has_rel. - DELETE FROM art_has_rel WHERE artrel_id=".$mysql->secure($artrel_id));
			throw new Exception("Error while deleting the art_has_rel.");
			return false;
		}
		else
		{
			return true;
		};
	}
	
	public static function cleanUp($rel_id=null, $art_id=null)
	{
			global $mysql;
			if (!empty($rel_id))
			{
				$mysql->query("DELETE FROM art_has_rel WHERE rel_id='".$mysql->secure($rel_id)."' ");
			} elseif (!empty($art_id))
			{
				$mysql->query("DELETE FROM art_has_rel WHERE art_id='".$mysql->secure($art_id)."' ");
			}
	}
	
	public static function getLastFromArtist($art_id)
	{
			global $mysql;
			$req_last = $mysql->query("SELECT artrel_order FROM art_has_rel WHERE art_id='".$mysql->secure($art_id)."' ORDER BY artrel_order DESC LIMIT 1");
			if($req_last->numRows() > 0)
			{
					$obj_last = $req_last->fetchRow();
					return $obj_last->artrel_order;
			} else
			{
				return 0;
			}
	}
}
?>